import {
  DocumentHealthAdditionsQuestionType,
  DocumentHealthAdditionsSanitizationDoorLockSystem,
  DocumentHealthAdditionsSanitizationMaterialsUsed,
  DocumentHealthAdditionsSanitizationVentilation,
  DocumentHealthSanitizationType,
} from "./types/document/enum";
import { IDocument } from "./types/document/interface";

export const document: Partial<IDocument> = {
  id: "req-1725289092400",
  attachments: {
    collect: {
      urls: ["image/req-1725291657748.png"],
    },
    contracts: {
      urls: ["image/req-1725291628413.png"],
    },
    licenses: {
      urls: ["application/req-1725291635696.pdf"],
    },
    photos: {
      urls: ["image/req-1725291644493.png"],
    },
    training: {
      urls: ["image/req-1725291652304.png"],
    },
  },
  wastes: [
    {
      id: "9844f7a6-eb7a-485c-800c-e4bc84a8a120",
      class: 0,
      classificationId: "20 02 01",
      collectionFrequency: 0,
      companyDestination: 0,
      companyTransport: 0,
      frequency: 2,
      originPoint: [9],
      packing: 7,
      quantity: 1.05,
      storage: 22,
      treatment: 0,
      unit: 0,
    },
    {
      id: "9844f7a6-eb7a-485c-800c-e4bc84a8a124",
      class: 1,
      classificationId: "20 02 01",
      collectionFrequency: 0,
      companyDestination: 0,
      companyTransport: 0,
      frequency: 2,
      originPoint: [9],
      packing: 7,
      quantity: 1.05,
      storage: 22,
      treatment: 0,
      unit: 0,
    },
    {
      id: "69455129-8b83-4482-a55c-f81b3887dfc0",
      class: 1,
      classificationId: "20 03 01",
      collectionFrequency: 0,
      companyDestination: 0,
      companyTransport: 0,
      frequency: 2,
      originPoint: [3],
      packing: 7,
      quantity: 32.5,
      storage: 22,
      treatment: 0,
      unit: 0,
    },
    {
      id: "64eda16f-e273-4626-a831-a5dac06010c4",
      class: 1,
      classificationId: "20 01 08",
      collectionFrequency: 0,
      companyDestination: 0,
      companyTransport: 0,
      frequency: 2,
      originPoint: [4],
      packing: 7,
      quantity: 90,
      storage: 22,
      treatment: 0,
      unit: 0,
    },
    {
      id: "61cfa3ad-a5de-4ff4-9b73-2ef73326d78c",
      class: 2,
      classificationId: "20 01 01",
      collectionFrequency: 0,
      companyDestination: 0,
      companyTransport: 0,
      frequency: 2,
      originPoint: [2, 4],
      packing: 1,
      quantity: 30,
      storage: 22,
      treatment: 10,
      unit: 0,
    },
    {
      id: "edf76864-a06a-41c8-a680-ac2022eecf25",
      class: 2,
      classificationId: "20 01 40",
      collectionFrequency: 0,
      companyDestination: 0,
      companyTransport: 0,
      frequency: 2,
      originPoint: [2, 4],
      packing: 1,
      quantity: 10,
      storage: 22,
      treatment: 10,
      unit: 0,
    },
    {
      id: "9fb2d2c9-dcb9-4d73-9ed2-b6aabf370586",
      class: 2,
      classificationId: "20 01 39",
      collectionFrequency: 0,
      companyDestination: 0,
      companyTransport: 0,
      frequency: 2,
      originPoint: [2, 4],
      packing: 1,
      quantity: 50,
      storage: 22,
      treatment: 10,
      unit: 0,
    },
    {
      id: "175a97da-dabe-4a84-9218-1d141b3a3938",
      class: 2,
      classificationId: "20 01 02",
      collectionFrequency: 0,
      companyDestination: 0,
      companyTransport: 0,
      frequency: 2,
      originPoint: [2, 4],
      packing: 1,
      quantity: 5,
      storage: 22,
      treatment: 10,
      unit: 0,
    },
  ],
  company: {
    businessName: "NOME FANTASIA DA EMPRESA EXEMPLO",
    activityDescription:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit.\n\nTotam cumque distinctio, deleniti eos debitis ex dolorum, odit, id magnam vitae aperiam libero corrupti.\n\nUt ex molestiae dignissimos. Nesciunt impedit eius ullam illo obcaecati enim! Aliquid et praesentium aperiam doloribus cumque blanditiis quidem dignissimos, debitis voluptates reprehenderit eligendi doloremque quia totam asperiores dolores repudiandae eveniet excepturi facilis.\n\nConsectetur quibusdam facere voluptas laborum voluptate commodi sequi rem inventore labore possimus rerum laboriosam corrupti quam enim in culpa, doloribus temporibus nostrum et dicta.\n\nModi sequi dolor repellat eveniet voluptatibus maxime numquam dignissimos ipsum iste exercitationem labore incidunt ullam, est quisquam excepturi, sunt facilis nemo, accusantium tempora.\n\nIste ipsum quia repellat rem vitae tempore quae atque, voluptas ipsa similique hic ducimus natus suscipit quisquam molestiae perspiciatis reprehenderit totam porro possimus commodi aut cumque necessitatibus quidem.\n\nRem, rerum! Eveniet laborum, pariatur sint autem amet, id aliquid aliquam deleniti, numquam vel cumque? Porro corrupti autem et expedita magni rem, dolorem error quae illo harum cumque.\n\nSunt ducimus eum officia, ipsum et molestiae reiciendis recusandae quo tempore illo soluta sit labore, commodi magni omnis, ut voluptate?\n\nDoloremque est labore rem commodi repellendus provident, id earum dolor perferendis consectetur fuga. Omnis eos voluptatum placeat cum exercitationem obcaecati ducimus.",
    address: {
      city: "Teresina",
      neighborhood: "Matadouro",
      number: 112,
      state: "PI",
      street: "Rua Zubambi",
      zip: "64004370",
    },
    builtArea: 231.23,
    cnaeId: "0111-3/99",
    cnaeIds: [
      "0112-1/02",
      "0112-1/99",
      "0111-3/01",
      "0111-3/03",
      "0133-4/11",
      "0133-4/08",
    ],
    email: "example@email.com.br",
    healthAppointmentsByDay: 8621,
    hoursDayEnd: "06:00",
    hoursDayStart: "00:15",
    identifier: "32214229000115",
    landline: "89872983787",
    name: "Teste razão social",
    othersWorkSchedule: [
      {
        hoursDayEnd: "18:15",
        hoursDayStart: "01:30",
        weekDays: [1],
      },
      {
        hoursDayEnd: "23:45",
        hoursDayStart: "12:15",
        weekDays: [6],
      },
    ],
    phone: "97878274872",
    refectory: {
      amount: 0,
      prepare: 3,
    },
    totalEmployeesCount: 13242,
    weekDays: [2, 4, 0],
  },
  createdAt: 1725289093,
  createdBy: "d21fcbe9-f488-4165-9ddc-ba10fec19f8a",
  documentStatus: 2,
  healthAdditions: {
    homeCare: "",
    sanitization: {
      effluent: {
        destination: "rede coletora do esgoto",
        public: false,
      },
      items: [
        {
          frequency: 1,
          procedure: 0,
          product: 0,
          protectionGear: 0,
          type: DocumentHealthSanitizationType.CONTAINER,
        },
        {
          frequency: 4,
          otherProduct: "jhfxs",
          procedure: 0,
          product: 99,
          protectionGear: 0,
          type: DocumentHealthSanitizationType.INTERNAL_STORAGE,
        },
      ],
    },
    storage: {
      area: 154.46,
      exists: true,
      questions: [
        {
          exists: false,
          type: 0,
        },
        {
          // description: "tile",
          description: DocumentHealthAdditionsSanitizationMaterialsUsed.TILE,
          exists: true,
          type: 1,
        },
        {
          description: DocumentHealthAdditionsSanitizationVentilation.NATURAL,
          exists: true,
          type: 2,
        },
        {
          description: DocumentHealthAdditionsSanitizationVentilation.NATURAL,
          exists: true,
          type: 3,
        },
        {
          description:
            DocumentHealthAdditionsSanitizationDoorLockSystem.KEY_LOCK,
          exists: true,
          type: 4,
        },
        {
          exists: true,
          public: false,
          type: 5,
        },
        {
          exists: true,
          type: 7,
        },
        {
          exists: true,
          type: 8,
        },
      ],
      shared: true,
      wasteByType: true,
      wasteClasses: [1, 4, 3],
      wasteTypesIdentification: true,
    },
  },
  healthWastes: [
    {
      id: "req-1725289693404",
      collectionFrequency: 4,
      companiesDestination: [
        {
          identifier: "61221672000111",
          license: "234234-234",
          licenseExpirationDate: 1727449602.644,
          name: "Empresa terceirizada responsável pelo infectante 1",
        },
        {
          identifier: "81986348000100",
          license: "9723498=234",
          licenseExpirationDate: 1758726440.808,
          name: "Empresa terceirizada responsável pelo tratamento do infectante 1",
        },
      ],
      companiesTransport: [
        {
          identifier: "61221672000111",
          license: "234234-234",
          licenseExpirationDate: 1727449602.644,
          name: "Empresa terceirizada responsável pelo infectante 1",
        },
      ],
      companyDestination: 2,
      companyTransport: 2,
      explant: {
        deliveredToPatient: {
          exists: false,
          description: "",
        },
        internalTreatment: false,
        procedures:
          "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum culpa illum, magni nobis quidem, corrupti perferendis molestias vero inventore esse eius, et dolore quam soluta laboriosam! Ipsum, assumenda reprehenderit.\n\nSunt velit hic natus, perferendis culpa dolorum, nisi et, eligendi explicabo blanditiis nam! Beatae non sit, voluptas at vero nisi ut quam totam ex quod libero sunt suscipit animi numquam facere reiciendis optio eligendi ab accusantium ullam corporis.\n\nVeritatis obcaecati iusto consequatur eum voluptates at vel numquam!\n\nPorro doloremque pariatur repellat dignissimos voluptas adipisci fugiat, repudiandae suscipit illo aliquid, earum magnam obcaecati nostrum inventore maiores, iure excepturi numquam rerum soluta voluptate.",
      },
      frequency: 2,
      group: 0,
      names: [
        "resíduo infectante 1",
        "resíduo infectante 2",
        "resíduo infectante 3",
        "resíduo infectante 4",
        "resíduo infectante 5",
        "resíduo infectante 6",
        "resíduo infectante 7",
      ],
      originPoints: [14, 11, 18, 13],
      packing: 0,
      putrescible: {
        coolingSystem: {
          exists: true,
          systemUsed: 2,
        },
        descriptions: [7, 5, 2, 9],
      },
      quantity: 123,
      treatment: 16,
      unit: 2,
    },
    {
      id: "req-1725289810650",
      collectionFrequency: 2,
      companiesDestination: [
        {
          identifier: "66682340000158",
          license: "9723498=234",
          licenseExpirationDate: 1758682800,
          name: "Empresa terceirizada responsável pelo tratamento do quimico 1",
        },
      ],
      companiesTransport: [
        {
          identifier: "16278203000184",
          license: "234234-234",
          licenseExpirationDate: 1727406000,
          name: "Empresa terceirizada responsável pelo transporte do quimico 1",
        },
      ],
      companyDestination: 2,
      companyTransport: 2,
      frequency: 1,
      group: 1,
      names: [
        "residuo quimico 1",
        "residuo quimico 2",
        "residuo quimico 3",
        "residuo quimico 4",
        "residuo quimico 5",
        "residuo quimico 6",
        "residuo quimico 7",
        "residuo quimico 8",
        "residuo quimico 9. residuo quimico 10",
        "residuo quimico 11",
      ],
      originPoints: [15, 18, 14, 13, 6, 8, 7],
      packing: 2,
      quantity: 9871,
      treatment: 5,
      unit: 0,
    },
    {
      id: "req-1725290031153",
      collectionFrequency: 2,
      companiesDestination: [
        {
          identifier: "64622800000127",
          license: "9723498=234",
          licenseExpirationDate: 1758682800,
          name: "Empresa terceirizada responsável pelo tratamento do não reciclável 1",
        },
      ],
      companiesTransport: [
        {
          identifier: "88562262000190",
          license: "234234-234",
          licenseExpirationDate: 1727406000,
          name: "Empresa terceirizada responsável pelo transporte do não reciclavel 1",
        },
      ],
      companyDestination: 2,
      companyTransport: 2,
      frequency: 1,
      group: 3,
      names: [
        "residuo não reciclável 1",
        "residuo não reciclável 2",
        "residuo não reciclável 3",
        "residuo não reciclável 4",
        "residuo não reciclável 5",
        "residuo não reciclável 6",
        "residuo não reciclável 7",
      ],
      originPoints: [0, 18, 13, 1, 15],
      packing: 5,
      quantity: 13,
      treatment: 2,
      unit: 4,
    },
    {
      id: "req-1725291146383",
      collectionFrequency: 5,
      companiesDestination: [
        {
          identifier: "32812554000180",
          license: "9723498=234",
          licenseExpirationDate: 1758682800,
          name: "Empresa terceirizada responsável pelo tratamento do reciclavel 2",
        },
      ],
      companiesTransport: [
        {
          identifier: "53872579000149",
          license: "9723498=234",
          licenseExpirationDate: 1758682800,
          name: "Empresa terceirizada responsável pelo transporte do reciclavel 1",
        },
      ],
      companyDestination: 2,
      companyTransport: 2,
      frequency: 6,
      group: 4,
      names: [
        "residuo reciclavel 1",
        "residuo reciclavel 2",
        "residuo reciclavel 3",
        "residuo reciclavel 4",
        "residuo reciclavel 5",
        "residuo reciclavel 6",
        "residuo reciclavel 7",
        "residuo reciclavel 8",
        "residuo reciclavel 9",
      ],
      originPoints: [15, 18, 0, 1],
      packing: 4,
      quantity: 927,
      treatment: 4,
      unit: 4,
    },
    {
      id: "req-1725291337355",
      chemicalDangerProcedures:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit.\n\nReprehenderit fuga alias error. Sapiente culpa sit ratione aliquam non vitae quibusdam eligendi nesciunt deleniti harum iure assumenda molestias qui eaque nisi similique ut modi, consequuntur accusantium, laudantium dolorem distinctio?\n\nA, dignissimos! Dicta beatae, tenetur voluptas porro, suscipit, itaque quibusdam tempore nesciunt similique fuga odit incidunt debitis possimus a aspernatur doloribus minus sit ad ex? Recusandae pariatur tempore animi id? Maiores, commodi?",
      collectionFrequency: 2,
      companiesDestination: [
        {
          identifier: "70527866000130",
          license: "9723498=234",
          licenseExpirationDate: 1758682800,
          name: "Empresa terceirizada responsável pelo tratamento do perfurocortante 2",
        },
      ],
      companiesTransport: [
        {
          identifier: "58523465000107",
          license: "234234-234",
          licenseExpirationDate: 1727406000,
          name: "Empresa terceirizada responsável pelo transporte do perfurocortante 1",
        },
      ],
      companyDestination: 2,
      companyTransport: 2,
      frequency: 6,
      group: 5,
      names: [
        "residuo perfurocortante 1",
        "residuo perfurocortante 2",
        "residuo perfurocortante 3",
        "residuo perfurocortante 4",
        "residuo perfurocortante 5",
        "residuo perfurocortante 6",
      ],
      originPoints: [0, 11, 18, 13],
      packing: 3,
      quantity: 764,
      treatment: 5,
      unit: 1,
    },
  ],
  healthWastesGroupC: {
    exists: true,
  },
  histories: [
    {
      date: 1725289097,
      description: "Documento em rascunho",
      text: "PGRSS iniciado",
      type: 2,
    },
    {
      date: 1725291715,
      description: "Documento enviado para o responsável técnico",
      text: "PGRSS enviado",
      type: 2,
    },
    {
      date: 1725291731,
      description: "Documento em análise pelo responsável técnico",
      text: "PGRSS em análise",
      type: 2,
    },
  ],
  rejected: {
    company:
      '- reduzir o tamanho do texto de "descrição das atividades"\n- Remover duas atividades secundárias',
  },
  responsibles: {
    implementation: {
      email: "email@example.com",
      name: "Nome do Responsável técnico pela implementação na empresa descrita nesse PGRSS",
      position: "Engenheiro",
      professionalClass: {
        identity: "987234-234",
        institution: "CRQ XX",
      },
      taxpayerNumber: "63346551326",
    },
    legal: {
      email: "email@example.com",
      name: "NOme completo do responsável pela empresa descrita nesse PGRSS",
      taxpayerNumber: "63346551326",
    },
  },
  status: 1,
  techinicalId: "43b2d7f3-665a-4aa1-b125-50a9db5ec559",
  techinicalName: "Vinicius Ramalho",
  templateRef: "default@pgrss",
  updatedAt: 1725298454,
  updatedBy: "d21fcbe9-f488-4165-9ddc-ba10fec19f8a",
  userId: "d21fcbe9-f488-4165-9ddc-ba10fec19f8a",
};
